### ISSUE TITLE
Support floats in the IR parser

### ISSUE THREAD

**Issue by asejfia** [google-research/raksha#634]
The epsilon and delta values for dp will be floats (they are usually very small values). The IR parser should support them eventually.

**Comment by asejfia** [comment]
@harsha-mandadi

**Comment by Cypher1** [comment]
I wrote up a quick draft of this in https://github.com/Cypher1/raksha/tree/parse_floats as I've been thinking about float/double parsing a bit (in my own time) lately. If you wanted to use it @harsha-mandadi that'd be fine by me, or I can open a PR for it and see if it meets @asejfia needs :)

**Comment by harsha-mandadi** [comment]
J, Thank you for working on this. Please go ahead and open a PR for the work you have already done. :) This looks similar to what @asejfia needs. (@asejfia to comment on this.)

**Comment by Cypher1** [comment]
I've opened a PR and added handling so that any of:
- a decimal point e.g. `0.`
- an exponent e.g. `0e1`
- or a suffix e.g. `3l` or `3f`

will result in the value being considered a floating point, and therefore a `double` (no `float` support at the moment as I'm not sure it would be helpful).

The syntax is intended to match the `Absl::Atod` and `printf("%g", double_value)` standards, but with added support for the trailing suffix to avoid ambiguity.

e.g.

`3e0` is a `double`.
`3.0` is a `double`.
`3l` is a `double`.
`3` is an `int`.

Happy to rework things as needed.
