### ISSUE TITLE
Cleanup AuthLogic.g4

### ISSUE THREAD

**Issue by harsha-mandadi** [google-research/raksha#661]
- ID : ('"')? [_a-zA-Z%][_a-zA-Z0-9/.#:]* ('"')?; 
- ID pattern should not include '"' or '%', instead quotes and '%' needs to be tokenized separately.

**Comment by aferr** [comment]
These are fixed in the latest [authlogic.g4 in the rust directory](https://github.com/google-research/raksha/blob/main/rust/tools/authorization-logic/src/parsing/AuthLogic.g4) as of [this pr](https://github.com/google-research/raksha/pull/593/files#diff-f485debf22070ea87700d2b589051e492d0a3a0f9e9084f854cd242dbaad38dd). You may want to just copy it over.

**Comment by aferr** [comment]
Oh I think I see what you mean about tokenizing " separately. Your point is to avoid having sanitizeID in `ast_construction_visitor`. In this case, yes this is not done yet and this would be an improvement :)
